# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.access_key_request_ssh import AccessKeyRequestSsh

class TestAccessKeyRequestSsh(unittest.TestCase):
    """AccessKeyRequestSsh unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessKeyRequestSsh:
        """Test AccessKeyRequestSsh
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessKeyRequestSsh`
        """
        model = AccessKeyRequestSsh()
        if include_optional:
            return AccessKeyRequestSsh(
                login = 'user',
                private_key = 'private key'
            )
        else:
            return AccessKeyRequestSsh(
        )
        """

    def testAccessKeyRequestSsh(self):
        """Test AccessKeyRequestSsh"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
