# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.inventory_request import InventoryRequest

class TestInventoryRequest(unittest.TestCase):
    """InventoryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryRequest:
        """Test InventoryRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryRequest`
        """
        model = InventoryRequest()
        if include_optional:
            return InventoryRequest(
                name = 'Test',
                project_id = 1,
                inventory = '',
                ssh_key_id = 1,
                become_key_id = 1,
                type = 'static'
            )
        else:
            return InventoryRequest(
        )
        """

    def testInventoryRequest(self):
        """Test InventoryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
