# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.project_project_id_users_user_id_put_request import ProjectProjectIdUsersUserIdPutRequest

class TestProjectProjectIdUsersUserIdPutRequest(unittest.TestCase):
    """ProjectProjectIdUsersUserIdPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectProjectIdUsersUserIdPutRequest:
        """Test ProjectProjectIdUsersUserIdPutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectProjectIdUsersUserIdPutRequest`
        """
        model = ProjectProjectIdUsersUserIdPutRequest()
        if include_optional:
            return ProjectProjectIdUsersUserIdPutRequest(
                role = 'owner'
            )
        else:
            return ProjectProjectIdUsersUserIdPutRequest(
        )
        """

    def testProjectProjectIdUsersUserIdPutRequest(self):
        """Test ProjectProjectIdUsersUserIdPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
