# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.view_request import ViewRequest

class TestViewRequest(unittest.TestCase):
    """ViewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewRequest:
        """Test ViewRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewRequest`
        """
        model = ViewRequest()
        if include_optional:
            return ViewRequest(
                title = 'Test',
                project_id = 1,
                position = 1
            )
        else:
            return ViewRequest(
        )
        """

    def testViewRequest(self):
        """Test ViewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
