# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.template_request import TemplateRequest

class TestTemplateRequest(unittest.TestCase):
    """TemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateRequest:
        """Test TemplateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateRequest`
        """
        model = TemplateRequest()
        if include_optional:
            return TemplateRequest(
                project_id = 1,
                inventory_id = 1,
                repository_id = 1,
                environment_id = 1,
                view_id = 1,
                vault_id = 1,
                name = 'Test',
                playbook = 'test.yml',
                arguments = '[]',
                description = 'Hello, World!',
                allow_override_args_in_task = False,
                limit = '',
                suppress_success_alerts = True,
                survey_vars = [
                    semaphore_api.models.template_survey_var.TemplateSurveyVar(
                        name = '', 
                        title = '', 
                        description = '', 
                        type = 'String => "", Integer => "int"', 
                        required = True, )
                    ]
            )
        else:
            return TemplateRequest(
        )
        """

    def testTemplateRequest(self):
        """Test TemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
