# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.info_type_update import InfoTypeUpdate

class TestInfoTypeUpdate(unittest.TestCase):
    """InfoTypeUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfoTypeUpdate:
        """Test InfoTypeUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InfoTypeUpdate`
        """
        model = InfoTypeUpdate()
        if include_optional:
            return InfoTypeUpdate(
                tag_name = ''
            )
        else:
            return InfoTypeUpdate(
        )
        """

    def testInfoTypeUpdate(self):
        """Test InfoTypeUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
