# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_events_get(self) -> None:
        """Test case for events_get

        Get Events related to Semaphore and projects you are part of
        """
        pass

    def test_events_last_get(self) -> None:
        """Test case for events_last_get

        Get last 200 Events related to Semaphore and projects you are part of
        """
        pass

    def test_info_get(self) -> None:
        """Test case for info_get

        Fetches information about semaphore
        """
        pass

    def test_ping_get(self) -> None:
        """Test case for ping_get

        PING test
        """
        pass

    def test_project_project_id_users_user_id_put(self) -> None:
        """Test case for project_project_id_users_user_id_put

        Update user role
        """
        pass

    def test_ws_get(self) -> None:
        """Test case for ws_get

        Websocket handler
        """
        pass


if __name__ == '__main__':
    unittest.main()
