# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.project_backup_templates_inner import ProjectBackupTemplatesInner

class TestProjectBackupTemplatesInner(unittest.TestCase):
    """ProjectBackupTemplatesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectBackupTemplatesInner:
        """Test ProjectBackupTemplatesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectBackupTemplatesInner`
        """
        model = ProjectBackupTemplatesInner()
        if include_optional:
            return ProjectBackupTemplatesInner(
                inventory = '',
                repository = '',
                environment = '',
                view = '',
                name = '',
                playbook = '',
                description = '',
                allow_override_args_in_task = True,
                suppress_success_alerts = True,
                autorun = True,
                type = ''
            )
        else:
            return ProjectBackupTemplatesInner(
        )
        """

    def testProjectBackupTemplatesInner(self):
        """Test ProjectBackupTemplatesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
