# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.user_put_request import UserPutRequest

class TestUserPutRequest(unittest.TestCase):
    """UserPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPutRequest:
        """Test UserPutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPutRequest`
        """
        model = UserPutRequest()
        if include_optional:
            return UserPutRequest(
                name = 'Integration Test User2',
                username = 'test-user2',
                email = 'test2@ansiblesemaphore.test',
                alert = True,
                admin = True
            )
        else:
            return UserPutRequest(
        )
        """

    def testUserPutRequest(self):
        """Test UserPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
