# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.integration_matcher import IntegrationMatcher

class TestIntegrationMatcher(unittest.TestCase):
    """IntegrationMatcher unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationMatcher:
        """Test IntegrationMatcher
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationMatcher`
        """
        model = IntegrationMatcher()
        if include_optional:
            return IntegrationMatcher(
                id = 56,
                integration_id = 56,
                name = 'deploy',
                match_type = 'body',
                method = 'equals',
                body_data_type = 'json',
                key = 'key',
                value = 'value'
            )
        else:
            return IntegrationMatcher(
        )
        """

    def testIntegrationMatcher(self):
        """Test IntegrationMatcher"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
