# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_projects_get(self) -> None:
        """Test case for projects_get

        Get projects
        """
        pass

    def test_projects_post(self) -> None:
        """Test case for projects_post

        Create a new project
        """
        pass

    def test_projects_restore_post(self) -> None:
        """Test case for projects_restore_post

        Restore Project
        """
        pass


if __name__ == '__main__':
    unittest.main()
