# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.template import Template

class TestTemplate(unittest.TestCase):
    """Template unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Template:
        """Test Template
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Template`
        """
        model = Template()
        if include_optional:
            return Template(
                id = 1,
                project_id = 1,
                inventory_id = 1,
                repository_id = 56,
                environment_id = 1,
                view_id = 1,
                name = 'Test',
                playbook = 'test.yml',
                arguments = '[]',
                description = 'Hello, World!',
                allow_override_args_in_task = False,
                suppress_success_alerts = True,
                app = ''
            )
        else:
            return Template(
        )
        """

    def testTemplate(self):
        """Test Template"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
