# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_auth_login_get(self) -> None:
        """Test case for auth_login_get

        Fetches login metadata
        """
        pass

    def test_auth_login_post(self) -> None:
        """Test case for auth_login_post

        Performs Login
        """
        pass

    def test_auth_logout_post(self) -> None:
        """Test case for auth_logout_post

        Destroys current session
        """
        pass

    def test_auth_oidc_provider_id_login_get(self) -> None:
        """Test case for auth_oidc_provider_id_login_get

        Begin OIDC authentication flow and redirect to OIDC provider
        """
        pass

    def test_auth_oidc_provider_id_redirect_get(self) -> None:
        """Test case for auth_oidc_provider_id_redirect_get

        Finish OIDC authentication flow, upon succes you will be logged in
        """
        pass

    def test_user_tokens_api_token_id_delete(self) -> None:
        """Test case for user_tokens_api_token_id_delete

        Expires API token
        """
        pass

    def test_user_tokens_get(self) -> None:
        """Test case for user_tokens_get

        Fetch API tokens for user
        """
        pass

    def test_user_tokens_post(self) -> None:
        """Test case for user_tokens_post

        Create an API token
        """
        pass


if __name__ == '__main__':
    unittest.main()
