# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.models.integration_extract_value_request import IntegrationExtractValueRequest

class TestIntegrationExtractValueRequest(unittest.TestCase):
    """IntegrationExtractValueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationExtractValueRequest:
        """Test IntegrationExtractValueRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationExtractValueRequest`
        """
        model = IntegrationExtractValueRequest()
        if include_optional:
            return IntegrationExtractValueRequest(
                name = 'deploy',
                value_source = 'body',
                body_data_type = 'json',
                key = 'key',
                variable = 'variable'
            )
        else:
            return IntegrationExtractValueRequest(
        )
        """

    def testIntegrationExtractValueRequest(self):
        """Test IntegrationExtractValueRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
