# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_api.api.integration_api import IntegrationApi


class TestIntegrationApi(unittest.TestCase):
    """IntegrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IntegrationApi()

    def tearDown(self) -> None:
        pass

    def test_project_project_id_integrations_integration_id_matchers_get(self) -> None:
        """Test case for project_project_id_integrations_integration_id_matchers_get

        Get Integration Matcher linked to integration extractor
        """
        pass

    def test_project_project_id_integrations_integration_id_matchers_matcher_id_delete(self) -> None:
        """Test case for project_project_id_integrations_integration_id_matchers_matcher_id_delete

        Removes integration matcher
        """
        pass

    def test_project_project_id_integrations_integration_id_matchers_matcher_id_put(self) -> None:
        """Test case for project_project_id_integrations_integration_id_matchers_matcher_id_put

        Updates Integration Matcher
        """
        pass

    def test_project_project_id_integrations_integration_id_values_extractvalue_id_delete(self) -> None:
        """Test case for project_project_id_integrations_integration_id_values_extractvalue_id_delete

        Removes integration extract value
        """
        pass

    def test_project_project_id_integrations_integration_id_values_extractvalue_id_put(self) -> None:
        """Test case for project_project_id_integrations_integration_id_values_extractvalue_id_put

        Updates Integration ExtractValue
        """
        pass

    def test_project_project_id_integrations_integration_id_values_get(self) -> None:
        """Test case for project_project_id_integrations_integration_id_values_get

        Get Integration Extracted Values linked to integration extractor
        """
        pass


if __name__ == '__main__':
    unittest.main()
