# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from semaphore_api.models.access_key_request_login_password import AccessKeyRequestLoginPassword
from semaphore_api.models.access_key_request_ssh import AccessKeyRequestSsh
from typing import Optional, Set
from typing_extensions import Self

class AccessKeyRequest(BaseModel):
    """
    AccessKeyRequest
    """ # noqa: E501
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    project_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    login_password: Optional[AccessKeyRequestLoginPassword] = None
    ssh: Optional[AccessKeyRequestSsh] = None
    __properties: ClassVar[List[str]] = ["name", "type", "project_id", "login_password", "ssh"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'ssh', 'login_password']):
            raise ValueError("must be one of enum values ('none', 'ssh', 'login_password')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessKeyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of login_password
        if self.login_password:
            _dict['login_password'] = self.login_password.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ssh
        if self.ssh:
            _dict['ssh'] = self.ssh.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessKeyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "project_id": obj.get("project_id"),
            "login_password": AccessKeyRequestLoginPassword.from_dict(obj["login_password"]) if obj.get("login_password") is not None else None,
            "ssh": AccessKeyRequestSsh.from_dict(obj["ssh"]) if obj.get("ssh") is not None else None
        })
        return _obj


