# coding: utf-8

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProjectBackupTemplatesInner(BaseModel):
    """
    ProjectBackupTemplatesInner
    """ # noqa: E501
    inventory: Optional[StrictStr] = None
    repository: Optional[StrictStr] = None
    environment: Optional[StrictStr] = None
    view: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    playbook: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    allow_override_args_in_task: Optional[StrictBool] = None
    suppress_success_alerts: Optional[StrictBool] = None
    autorun: Optional[StrictBool] = None
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["inventory", "repository", "environment", "view", "name", "playbook", "description", "allow_override_args_in_task", "suppress_success_alerts", "autorun", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectBackupTemplatesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectBackupTemplatesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "inventory": obj.get("inventory"),
            "repository": obj.get("repository"),
            "environment": obj.get("environment"),
            "view": obj.get("view"),
            "name": obj.get("name"),
            "playbook": obj.get("playbook"),
            "description": obj.get("description"),
            "allow_override_args_in_task": obj.get("allow_override_args_in_task"),
            "suppress_success_alerts": obj.get("suppress_success_alerts"),
            "autorun": obj.get("autorun"),
            "type": obj.get("type")
        })
        return _obj


