name: Check version

on:
  #schedule:
  #  - cron: '*/5 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/check-version.yml'
      
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout branch "master"
        uses: actions/checkout@v4
      - name: "Call API"
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url: https://api.github.com/repos/ansible-semaphore/semaphore/releases/latest
          method: "GET"
          log-response: true


      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'
      - name: "Use response"
        run: |
          version=`echo ${{ steps.api.outputs.response }} | jq -r '.name' | sed 's/^v//'`
          echo $version
          ## echo ${{ steps.api.outputs.response }} | jq -r '.name' | sed 's/^v//'
