name: Check version

on:
  #schedule:
  #  - cron: '*/5 * * * *'
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/check-version.yml'
      
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout branch "master"
        uses: actions/checkout@v4
      
      - name: Extract version from API response
        run: |
          PAGE_SEMAPHORE_VERSION=$(curl -s https://api.github.com/repos/ansible-semaphore/semaphore/releases/latest | jq -r '.name' | sed 's/^v//')
          echo "Extracted version: $PAGE_SEMAPHORE_VERSION"
          cat "PAGE_SEMAPHORE_VERSION=$PAGE_SEMAPHORE_VERSION" >> "$GITHUB_ENV"
        shell: bash

      - name: Read variable.env and set variable
        id: read-version
        run: |
          cat variable.env
          cat variable.env >> "$GITHUB_ENV"

      - name: Extract version from API response
        run: |      
          if [ "$PAGE_SEMAPHORE_VERSION" != "$SEMAPHORE_VERSION" ]; then
            echo "Versions are different. Updating SEMAPHORE_VERSION to PAGE_SEMAPHORE_VERSION."
            echo "SEMAPHORE_VERSION=$PAGE_SEMAPHORE_VERSION" > variable.env

          else
            echo "Versions are the same. No update needed."
          fi
      
          echo "Final SEMAPHORE_VERSION: $SEMAPHORE_VERSION"
        shell: bash
    
      - name: Extract version from API response
        run: |      
         cat variable.env
        shell: bash
