name: Check version

on:
  #schedule:
  #  - cron: '*/5 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/check-version.yml'
      
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "$(date +'%Y-%m-%d')"
        
      - name: Checkout branch "master"
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Extract version from Ansible Semaphore Github API response
        run: |
          PAGE_SEMAPHORE_VERSION=$(curl -s https://api.github.com/repos/ansible-semaphore/semaphore/releases/latest | jq -r '.name' | sed 's/^v//')
          echo "Extracted version: $PAGE_SEMAPHORE_VERSION"
          echo "PAGE_SEMAPHORE_VERSION=$PAGE_SEMAPHORE_VERSION" >> "$GITHUB_ENV"
        shell: bash

      - name: Read variable.env and set env variable
        id: read-version
        run: |
          cat variable.env
          cat variable.env >> "$GITHUB_ENV"

      - name: Compare versions
        run: |      
          if [ "$PAGE_SEMAPHORE_VERSION" != "$SEMAPHORE_VERSION" ]; then
            echo "Versions are different. Updating SEMAPHORE."
            echo "PYPI_NAME=semaphore_api" > variable.env
            echo "SEMAPHORE_VERSION=$PAGE_SEMAPHORE_VERSION" >> variable.env
            echo "PYPI_VERSION=$PAGE_SEMAPHORE_VERSION" >> variable.env
          else
            echo "Versions are the same. No update needed."
            exit 0
          fi
      
          echo "Final SEMAPHORE set: $PAGE_SEMAPHORE_VERSION"
        shell: bash
    
      - name: Print new file version
        run: |      
         cat variable.env
        shell: bash

      - name: Commit changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "github@nchekwa.com"
          git status
          git add variable.env
          git commit -am "GitHub Actions Check Version Update $(date +"%Y-%m-%d %H:%M:%S")"
          git push -f origin main


