name: Check version

on:
  #schedule:
  #  - cron: '*/5 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/check-version.yml'
      
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout branch "master"
        uses: actions/checkout@v4
      
      - name: Extract version from API response
        run: |
          SEMAPHORE_VERSION=$(curl -s https://api.github.com/repos/ansible-semaphore/semaphore/releases/latest | jq -r '.name' | sed 's/^v//')
          echo "Extracted version: $SEMAPHORE_VERSION"
        shell: bash
        
      - name: Extract version from API response
        run: |
          SEMAPHORE_VERSION2=$(curl -s https://api.github.com/repos/ansible-semaphore/semaphore/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "Extracted version: $SEMAPHORE_VERSION2"
        shell: bash
