name: Get Global Variables
#run-name: Variables

on:
  workflow_dispatch:
    inputs:
      file:
        description: "File name with variables"
        required: false
        type: string
        default: "variable.env"
  workflow_call:
    inputs:
      file:
        description: "File name with variables"
        required: false
        type: string
        default: "variable.env"
    outputs:
      PYPI_NAME:
        description: "PyPi module name"
        value: ${{ jobs.vars.outputs.PYPI_NAME }}
      PYPI_VERSION:
        description: "PyPi version which we going to build"
        value: ${{ jobs.vars.outputs.PYPI_VERSION }}
      SEMAPHORE_VERSION:
        description: "Ansible Semaphore API Version which we check"
        value: ${{ jobs.vars.outputs.SEMAPHORE_VERSION }}

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Read .env file and set variable and output
      id: read-variable-env-file
      run: |
        cat ${{ inputs.file }} 
        cat ${{ inputs.file }} >> "$GITHUB_ENV"
    
    outputs:
      PYPI_NAME: ${{ env.PYPI_NAME }}
      PYPI_VERSION: ${{ env.PYPI_VERSION }}
      SEMAPHORE_VERSION: ${{ env.SEMAPHORE_VERSION }}
