name: Github Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          # secrets.GITHUB_TOKEN - This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Ref to Ansible-Semaphore Release Notes [v${{ github.ref }}](https://github.com/ansible-semaphore/semaphore/releases/tag/v${{ github.ref }})
          draft: false
          prerelease: false

      - name: Publish distribution 📦 to Github Release ${{ github.ref }}
        uses: xresloader/upload-to-github-release@main
        if: env.PYPI_BLOCK != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
