# coding: utf-8

# flake8: noqa

"""
    SEMAPHORE

    Semaphore API

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from semaphore_api.api.authentication_api import AuthenticationApi
from semaphore_api.api.default_api import DefaultApi
from semaphore_api.api.integration_api import IntegrationApi
from semaphore_api.api.project_api import ProjectApi
from semaphore_api.api.projects_api import ProjectsApi
from semaphore_api.api.schedule_api import ScheduleApi
from semaphore_api.api.user_api import UserApi

# import ApiClient
from semaphore_api.api_response import ApiResponse
from semaphore_api.api_client import ApiClient
from semaphore_api.configuration import Configuration
from semaphore_api.exceptions import OpenApiException
from semaphore_api.exceptions import ApiTypeError
from semaphore_api.exceptions import ApiValueError
from semaphore_api.exceptions import ApiKeyError
from semaphore_api.exceptions import ApiAttributeError
from semaphore_api.exceptions import ApiException

# import models into sdk package
from semaphore_api.models.api_token import APIToken
from semaphore_api.models.access_key import AccessKey
from semaphore_api.models.access_key_request import AccessKeyRequest
from semaphore_api.models.access_key_request_login_password import AccessKeyRequestLoginPassword
from semaphore_api.models.access_key_request_ssh import AccessKeyRequestSsh
from semaphore_api.models.environment import Environment
from semaphore_api.models.environment_request import EnvironmentRequest
from semaphore_api.models.event import Event
from semaphore_api.models.info_type import InfoType
from semaphore_api.models.info_type_update import InfoTypeUpdate
from semaphore_api.models.integration import Integration
from semaphore_api.models.integration_extract_value import IntegrationExtractValue
from semaphore_api.models.integration_extract_value_request import IntegrationExtractValueRequest
from semaphore_api.models.integration_matcher import IntegrationMatcher
from semaphore_api.models.integration_matcher_request import IntegrationMatcherRequest
from semaphore_api.models.integration_request import IntegrationRequest
from semaphore_api.models.inventory import Inventory
from semaphore_api.models.inventory_request import InventoryRequest
from semaphore_api.models.login import Login
from semaphore_api.models.login_metadata import LoginMetadata
from semaphore_api.models.login_metadata_oidc_providers_inner import LoginMetadataOidcProvidersInner
from semaphore_api.models.project import Project
from semaphore_api.models.project_backup import ProjectBackup
from semaphore_api.models.project_backup_environments_inner import ProjectBackupEnvironmentsInner
from semaphore_api.models.project_backup_inventories_inner import ProjectBackupInventoriesInner
from semaphore_api.models.project_backup_keys_inner import ProjectBackupKeysInner
from semaphore_api.models.project_backup_meta import ProjectBackupMeta
from semaphore_api.models.project_backup_repositories_inner import ProjectBackupRepositoriesInner
from semaphore_api.models.project_backup_templates_inner import ProjectBackupTemplatesInner
from semaphore_api.models.project_backup_views_inner import ProjectBackupViewsInner
from semaphore_api.models.project_project_id_put_request import ProjectProjectIdPutRequest
from semaphore_api.models.project_project_id_role_get200_response import ProjectProjectIdRoleGet200Response
from semaphore_api.models.project_project_id_tasks_post_request import ProjectProjectIdTasksPostRequest
from semaphore_api.models.project_project_id_users_post_request import ProjectProjectIdUsersPostRequest
from semaphore_api.models.project_project_id_users_user_id_put_request import ProjectProjectIdUsersUserIdPutRequest
from semaphore_api.models.project_request import ProjectRequest
from semaphore_api.models.project_user import ProjectUser
from semaphore_api.models.repository import Repository
from semaphore_api.models.repository_request import RepositoryRequest
from semaphore_api.models.runner import Runner
from semaphore_api.models.schedule import Schedule
from semaphore_api.models.schedule_request import ScheduleRequest
from semaphore_api.models.task import Task
from semaphore_api.models.task_output import TaskOutput
from semaphore_api.models.template import Template
from semaphore_api.models.template_request import TemplateRequest
from semaphore_api.models.template_survey_var import TemplateSurveyVar
from semaphore_api.models.user import User
from semaphore_api.models.user_put_request import UserPutRequest
from semaphore_api.models.user_request import UserRequest
from semaphore_api.models.users_user_id_password_post_request import UsersUserIdPasswordPostRequest
from semaphore_api.models.view import View
from semaphore_api.models.view_request import ViewRequest
